env:
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
plugins:
  - '@typescript-eslint'
  - 'prettier'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
rules:
  'no-constant-condition': 'off'
ignorePatterns:
  - 'node_modules'
  - 'dist'
