name: Release

on:
  pull_request:
    branches: [ "main" ]
  # create:
  #   tags:
  #     - "*"

# TODO: checkout to tagged commit

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup
        uses: './.github/actions/setup'

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup
        uses: './.github/actions/setup'

      - name: Run typecheck
        run: pnpm typecheck

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup
        uses: './.github/actions/setup'

      - name: Run lint
        run: pnpm lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup
        uses: './.github/actions/setup'

      - name: Generate files
        run: pnpm pregenerate-files

      - name: Run tests
        run: pnpm test
  
  publish:
    needs: [typecheck, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup
        uses: './.github/actions/setup'

      - name: Build
        run: pnpm build
      
      # - name: Publish package
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
